### ISSUE TITLE
The Sign-out button should change after user logs in 

### ISSUE THREAD

**Issue by dineshshetye** [Empressinfotech/HPCCInfo#13]
This is an intermittent issue and cannot be reproduced at will. After log in, sometimes the Sign-in button does not change to Sign-out.

![image](https://user-images.githubusercontent.com/1731313/35881563-35674bd8-0b4f-11e8-9882-a347fc13715f.png)

**Comment by Empressinfotech** [comment]
Fixed on PR#36
