### ISSUE TITLE
Update Interactions not working

### ISSUE THREAD

**Issue by dineshshetye** [Empressinfotech/HPCCInfo#32]
Create an interaction between charts, save the interaction and view the charts. Then edit that interaction and view the charts. The interaction does not work. Now Open the edit interaction dialog and the parent chart is not populated.

![image](https://user-images.githubusercontent.com/1731313/35986905-5c55621e-0cc8-11e8-8f72-88abb33b0c53.png)

**Comment by Empressinfotech** [comment]
Fixed in PR #35
